name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/adhookio/docker-postgres-gcp-backup/docker-postgres-gcp-backup:latest && docker push -u ${{ secrets.PUBLISH_USER }} -p {{ secrets.PUBLISH_PASSWORD }} docker push docker.pkg.github.com/adhookio/docker-postgres-gcp-backup/docker-postgres-gcp-backup:latest
